source_path: "F:/01.감염병데이터베이스/data/2024_infectious_DW"
CDM_path: "F:/01.감염병데이터베이스/data/2024_infectious_CDM_folder"
source_encoding: "utf-8"
cdm_encoding: "utf-8-sig"
source_dtype: "str"
target_zip: "549"
data_range: "2023-12-31"
care_site_data: "care_site"
person_data: "person"
provider_data: "provider"
visit_data: "visit_occurrence"
visit_detail_data: "visit_detail"
local_kcd_data: "local_kcd"
local_edi_data: "local_edi"
person_source_value: "PATNO"
location_data: "location"
concept_unit: "concept_unit"
concept_etc: "concept_etc"
concept_kcd: "concept_kcd7"
unit_concept_synonym: "unit_concept_synonym"
diag_condition: "A9380"
# ['A9380', 'A753', 'A31']
no_matching_concept: [0, "No matching concept"]

# DQ
excel_path: "QC/품질진단지표.xlsx"
sheet_table_count: "원본비교결과"
sheet_field_summary: "컬럼별데이터분포진단"
sheet_dq: "점검사항"
sheet_meta: "메타데이터진단"

care_site:
  data:
    source_data: "ods_ccdeptct"
    output_filename: "care_site"
  columns:
    care_site_name: "DEPTLNM"
    place_of_service_concept_id: 0
    care_site_source_value: "DEPTCODE"
    place_of_service_source_value: "SUBDEPT"
    location_source_value: "LOCATION_SOURCE_VALUE"

provider:
  data:
    source_data: "dd_csusermt"
    output_filename: "provider"
  columns:
    provider_name: "USERNAME"
    provider_source_value: "USERID"
    specialty_source_value: JIKJONG
    specialty_source_value_name: "JIKJONGNM"
    gender_source_value: null
    care_site_source_value: DEPTCODE

person:
  data:
    source_data: "ods_appatbat"
    source_condition: "dw_mmpdiagt"
    output_filename: "person"
  columns:
    gender_source_value: "SEX"
    death_datetime: "DIEDATE"
    birth_resno1: "RESNO1"
    birth_resno2: "RESNO2"
    person_name: "PATNAME"
    location_source_value: "ZIPCODE"
    abotyp: ABOTYP
    rhtyp: RHTYP
    # 상병코드가 있을 경우 상병코드 컬럼 내용
    diagcode: "DIAGCODE"
    ruleoutyn: "RULEOUTYN"
    diagfg: "DIAGFG"

visit_occurrence:
  data:
    source_data: "ods_apopdlst"
    source_data2: "ods_apipdlst"
    output_filename: "visit_occurrence"
  columns:
    admitted_from_source_value: "ADMPATH"
    discharge_to_source_value: "DSCHRSLT"
    visit_source_value: "PATFG"
    medtime: "MEDTIME"
    admtime: "ADMTIME"
    dschtime: "DSCHTIME"
    meddept: "MEDDEPT"
    meddr: "MEDDR"
    chadr: "CHADR"

visit_detail:
  data:
   source_data: "ods_mnicupat"
   output_filename: "visit_detail"
  columns:
    visit_detail_start_datetime: "ENTRTIME"
    visit_detail_end_datetime: "OUTRMTIME"
    visit_detail_source_value: "ICU"
    admitted_from_source_value: "ENTRPATH"
    discharge_to_source_value: "DSCHSTATE"
    meddept: "MEDDEPT"
    provider: "CHADR"
    wardno: "WARDNO"
    icu_list: ['6002','5002','1005','2008','1002','2002','1003','1004','2003','2004','2007','5004','SI','ICU1','ICU2','ICU3']

local_kcd:
  data: 
    source: ods_sidiagct
    output_filename: local_kcd
  columns:
    diagcode: DIAGCODE
    fromdate: FROMDATE
    todate: TODATE
    engname: ENGNAME
    korname: KORNAME
    stdiagcd: STDIAGCD
    kcdversion: KCDVERSION
    # columns in concept table
    concept_id: concept_id
    concept_name: concept_name
    domain_id: domain_id
    vocabulary_id: vocabulary_id
    concept_class_id: concept_class_id
    standard_concept: standard_concept
    concept_code: concept_code
    valid_start_date: valid_start_date
    valid_end_date: valid_end_date
    invalid_reason: invalid_reason


condition_occurrence:
  data:
    source_data: "dw_mmpdiagt"
    output_filename: "condition_occurrence"  
  columns:
    meddept: "MEDDEPT"
    provider: "CHADR"
    condition_start_datetime: "MEDTIME"
    condition_type: MAINYN
    condition_source_value: "DIAGCODE"
    condition_source_value_name: "DIAGNAME"
    condition_status_source_value: IMPRESSYN
    patfg: "PATFG"
    diagfg: "DIAGFG"
    # local_kcd파일의 컬럼 정의
    fromdate: FROMDATE
    todate: TODATE


local_edi:
  data:
    order_data: "ods_mmordrct"
    edi_data: "ods_aipricst"
    concept_data: "concept_EDI_KDC"
    atc_data: "edi_atc"
    output_filename: "local_edi"
  columns:
    ordercode: "ORDCODE"
    ordname: "ORDNAME"
    sugacode: "SUGACODE"
    edicode: "INSEDICODE"
    fromdate: "FROMDATE"
    todate: "TODATE"
    standard_code: "표준코드"
    atccode: "ATC코드"
    atcname: "ATC 코드명"
    edi_fromdate: "품목허가일자"
    edi_todate: "취소일자"


drug_exposure:
  data:
    source_data: "dw_mmcuhort_med"
    output_filename: "drug_exposure"
  columns:
    meddept: "MEDDEPT"
    provider: "CHADR"
    drug_exposure_start_datetime: "ORDDATE"
    drug_source_value: "ORDCODE"
    days_supply: "DAY"
    qty: "CONTQTY"
    cnt: "CNT"
    dose_unit_source_value: "CONTUNIT"
    medtime: "MEDTIME"
    dcyn: "DCYN"
    patfg: "PATFG"
    drug_source_value_name: "ORDNAME"
    methodcd: "METHODCD"
    age: "AGE"
    ordseqno: "ORDSEQNO"
    # local_edi파일의 컬럼 정의
    fromdate: FROMDATE
    todate: TODATE
    ordcode: ORDCODE
    insedicode: INSEDICODE
    atccode: "ATC코드"
    atccodename: "ATC 코드명"


measurement_stexmrst:
  data:
    source_data: "dw_stexmrst"
    output_filename: "measurement_stexmrst"
  columns:
    meddept: "MEDDEPT"
    provider: "ORDDR"
    orddate: "ORDDATE"
    exectime: "EXECDT"
    measurement_source_value: "EXAMCODE"
    value_source_value: "RSLTNUM"
    unit_source_value: "RSLTUNIT"
    range_low: "NORLOW"
    range_high: "NORHIGH"
    patfg: "PATFG"
    medtime: "MEDTIME"
    ordseqno: "ORDSEQNO"
    age: "AGE"
    처방코드: "ORDCODE"
    처방명: "ORDNAME"
    결과내역: RSLTTEXT
    acptdt: "ACPTDT"
    readdt: "READDT"
    reptdt: "REPTDT"
    # local_edi파일의 컬럼 정의
    fromdate: FROMDATE
    todate: TODATE
    ordcode: ORDCODE
    insedicode: INSEDICODE
    ordname: ORDNAME


measurement_vs:
  data:
    source_data: "dv_basexm"
    output_filename: "measurement_vs"
  columns:
    admtime: "ADMTIME"
    measurement_datetime: "RECTIME"
    meddept: "MEDDEPT"
    patfg: "PATFG"
    height: "HT"
    weight: "WT"
    bmi: "BMI"
    sbp: "SBP"
    dbp: "DBP"
    pr: "PR"
    rr: "RR"
    bt: "BT"
    spo2: "SPO2"

merge_measurement:
  data:
    source_data1: "measurement_stexmrst"
    source_data2: "measurement_vs"
    output_filename: "measurement"

procedure_order:
  data:
    source_data: "dw_mmcuhort_etc"
    output_filename: "procedure_order"
  columns:
    meddept: "MEDDEPT"
    provider: "ORDDR"
    orddate: "ORDDATE"
    exectime: "EXECTIME"
    opdate: "OPDATE"
    procedure_source_value: "ORDCODE"
    procedure_source_value_name: "ORDNAME"
    patfg: "PATFG"
    medtime: "MEDTIME"
    dcyn: "DCYN"
    ordclstyp: "ORDCLSTYP"
    ordseqno: "ORDSEQNO"
    age: "AGE"
    # local_edi파일의 컬럼 정의
    fromdate: FROMDATE
    todate: TODATE
    ordcode: ORDCODE
    insedicode: INSEDICODE

procedure_stexmrst:
  data:
    source_data: "dw_stexmrst"
    output_filename: "procedure_stexmrst"
  columns:
    meddept: "MEDDEPT"
    provider: "ORDDR"
    orddate: "ORDDATE"
    exectime: "EXECTIME"
    procedure_source_value: "EXAMCODE"
    value_source_value: "RSLTNUM"
    unit_source_value: "RSLTUNIT"
    range_low: "NORLOW"
    range_high: "NORHIGH"
    patfg: "PATFG"
    medtime: "MEDTIME"
    ordseqno: "ORDSEQNO"
    age: "AGE"
    rslttext: "RSLTTEXT"
    conclusion: "CONCLUSION"
    ordcode: "ORDCODE"
    ordname: "ORDNAME"
    acptdt: "ACPTDT"
    readdt: "READDT"
    reptdt: "REPTDT"
    # local_edi파일의 컬럼 정의
    fromdate: FROMDATE
    todate: TODATE
    ordcode: ORDCODE
    insedicode: INSEDICODE
    ordname: ORDNAME

merge_procedure:
  data:
    source_data1: "procedure_order"
    source_data2: "procedure_stexmrst"
    output_filename: "procedure_occurrence"

observation_period:
  data:
    visit: "visit_occurrence"
    condition: "condition_occurrence"
    drug: "drug_exposure"
    measurement: "measurement"
    procedure: "procedure_occurrence"
    output_filename: "observation_period"

metadata:
  wbc_count: ['L200201']
  hb: ['L200203']
  hematocrit: ['L200204']
  platelet_count: ['L200209']
  lymphocyte_count: ['L200316']
  monocyte_count: ['L200317']
  neurophil_count: ['L200318']
  sodium: ['L3010', 'L7111']
  potassium: ['L3011', 'L7112']
  ast: ['L3015']
  alt: ['L3016']
  total_bilirubin: ['L3018']
  total_protein: ['L3020']
  albumin: ['L3021']
  bun: ['L3024']
  creatinine: ['L3025', 'L3025C']
  egfr: ['L3025R']
  crp: ['L3052']
  troponin_i: ['L3301', 'L7131']
  ck_mb: ['L3302']
  ph: ['L100202', 'L700202', 'L100404']
  paco2: ['LP100102']
  pao2: ['LP100103']
  arterial_ph: ['LP100101']
  # vs는 concept_id로 조회
  temperature: [4302666]
  sbp: [4152194]
  dbp: [4154790]
  heartrate: [4224504]
  respiratory_rate: [4313591]
  bmi: [40490382]
  height: [4177340]
  weight: [4099154]
