source_path: "F:/01.감염병데이터베이스/data/2024_infectious_DW"
CDM_path: "F:/01.감염병데이터베이스/data/2024_infectious_CDM"
encoding: "utf-8"
source_dtype: "str"
target_zip: "549"
data_range: "2023-12-31"
care_site_data: "care_site"
person_data: "person"
provider_data: "provider"
visit_data: "visit_occurrence"
visit_detail_data: "visit_detail"
local_edi_data: "local_edi"
person_source_value: "PATNO"
location_data: "location"
concept_unit: "concept_unit"
concept_etc: "concept_etc"
unit_concept_synonym: "unit_concept_synonym"
excel_path: "QC/품질진단지표.xlsx"
sheet_table_count: "원본비교결과"
sheet_field_summary: "컬럼별데이터분포진단"

care_site:
  data:
    source_data: "ods_ccdeptct"
    output_filename: "care_site"
  columns:
    care_site_name: "DEPTLNM"
    place_of_service_concept_id: 0
    care_site_source_value: "DEPTCODE"
    place_of_service_source_value: "SUBDEPT"
    location_source_value: "LOCATION_SOURCE_VALUE"

provider:
  data:
    source_data: "dd_csusermt"
    output_filename: "provider"
  columns:
    provider_name: "USERNAME"
    provider_source_value: "USERID"
    specialty_source_value: JIKJONG
    specialty_source_value_name: "JIKJONGNM"
    gender_source_value: null
    care_site_source_value: DEPTCODE

person:
  data:
    source_data: "ods_appatbat"
    output_filename: "person"
  columns:
    gender_source_value: "SEX"
    death_datetime: "DIEDATE"
    birth_resno1: "RESNO1"
    birth_resno2: "RESNO2"
    person_name: "PATNAME"
    location_source_value: "ZIPCODE"
    abotyp: ABOTYP
    rhtyp: RHTYP

visit_occurrence:
  data:
    source_data: "ods_apopdlst"
    source_data2: "ods_apipdlst"
    output_filename: "visit_occurrence"
  columns:
    admitted_from_source_value: "ADMPATH"
    discharge_to_source_value: "DSCHRSLT"
    visit_source_value: "PATFG"
    medtime: "MEDTIME"
    admtime: "ADMTIME"
    dschtime: "DSCHTIME"
    meddept: "MEDDEPT"
    meddr: "MEDDR"
    chadr: "CHADR"

visit_detail:
  data:
   source_data: "ods_mnicupat"
   output_filename: "visit_detail"
  columns:
    visit_detail_start_datetime: "ENTRTIME"
    visit_detail_end_datetime: "OUTRMTIME"
    visit_detail_source_value: "ICU"
    admitted_from_source_value: "ENTRPATH"
    discharge_to_source_value: "DSCHSTATE"
    meddept: "MEDDEPT"
    provider: "CHADR"
 
condition_occurrence:
  data:
    source_data: "dw_mmpdiagt"
    output_filename: "condition_occurrence"  
  columns:
    meddept: "MEDDEPT"
    provider: "CHADR"
    condition_start_datetime: "MEDTIME"
    condition_type: MAINYN
    condition_source_value: "DIAGCODE"
    condition_source_value_name: "DIAGNAME"
    condition_status_source_value: IMPRESSYN
    patfg: "PATFG"
    diagfg: "DIAGFG"


local_edi:
  data:
    order_data: "ods_mmordrct"
    edi_data: "ods_aipricst"
    concept_data: "concept_EDI_KDC"
    atc_data: "edi_atc"
    output_filename: "local_edi"
  columns:
    ordercode: "ORDCODE"
    sugacode: "SUGACODE"
    edicode: "INSEDICODE"
    fromdate: "FROMDATE"
    todate: "TODATE"
    standard_code: "표준코드"
    atccode: "ATC코드"
    atcname: "ATC 코드명"
    edi_fromdate: "품목허가일자"
    edi_todate: "취소일자"


drug_exposure:
  data:
    source_data: "dw_mmcuhort_med"
    output_filename: "drug_exposure"
  columns:
    meddept: "MEDDEPT"
    provider: "CHADR"
    drug_exposure_start_datetime: "ORDDATE"
    drug_source_value: "ORDCODE"
    days_supply: "DAY"
    qty: "CONTQTY"
    cnt: "CNT"
    dose_unit_source_value: "CONTUNIT"
    medtime: "MEDTIME"
    dcyn: "DCYN"
    patfg: "PATFG"
    drug_source_value_name: "ORDNAME"
    methodcd: "METHODCD"
    age: "AGE"
    ordseqno: "ORDSEQNO"


measurement_stexmrst:
  data:
    source_data: "dw_stexmrst"
    output_filename: "measurement_stexmrst"
  columns:
    meddept: "MEDDEPT"
    provider: "ORDDR"
    orddate: "ORDDATE"
    exectime: "EXECDT"
    measurement_source_value: "EXAMCODE"
    value_source_value: "RSLTNUM"
    unit_source_value: "RSLTUNIT"
    range_low: "NORLOW"
    range_high: "NORHIGH"
    patfg: "PATFG"
    medtime: "MEDTIME"
    ordseqno: "ORDSEQNO"
    age: "AGE"
    처방코드: "ORDCODE"
    처방명: "ORDNAME"
    결과내역: RSLTTEXT


measurement_vs:
  data:
    source_data: "dv_basexm"
    output_filename: "measurement_vs"
  columns:
    admtime: "ADMTIME"
    measurement_datetime: "RECTIME"
    meddept: "MEDDEPT"
    patfg: "PATFG"
    height: "HT"
    weight: "WT"
    bmi: "BMI"
    sbp: "SBP"
    dbp: "DBP"
    pr: "PR"
    rr: "RR"
    bt: "BT"
    spo2: "SPO2"

merge_measurement:
  data:
    source_data1: "measurement_stexmrst"
    source_data2: "measurement_vs"
    output_filename: "measurement"

procedure_order:
  data:
    source_data: "dw_mmcuhort_etc"
    output_filename: "procedure_order"
  columns:
    meddept: "MEDDEPT"
    provider: "ORDDR"
    orddate: "ORDDATE"
    exectime: "EXECTIME"
    opdate: "OPDATE"
    procedure_source_value: "ORDCODE"
    procedure_source_value_name: "ORDNAME"
    patfg: "PATFG"
    medtime: "MEDTIME"
    dcyn: "DCYN"
    ordclstyp: "ORDCLSTYP"
    ordseqno: "ORDSEQNO"
    age: "AGE"

procedure_stexmrst:
  data:
    source_data: "dw_stexmrst"
    output_filename: "procedure_stexmrst"
  columns:
    meddept: "MEDDEPT"
    provider: "ORDDR"
    orddate: "ORDDATE"
    exectime: "EXECTIME"
    procedure_source_value: "EXAMCODE"
    value_source_value: "RSLTNUM"
    unit_source_value: "RSLTUNIT"
    range_low: "NORLOW"
    range_high: "NORHIGH"
    patfg: "PATFG"
    medtime: "MEDTIME"
    ordseqno: "ORDSEQNO"
    age: "AGE"
    rslttext: "RSLTTEXT"
    conclusion: "CONCLUSION"
    ordcode: "ORDCODE"
    ordname: "ORDNAME"

merge_procedure:
  data:
    source_data1: "procedure_order"
    source_data2: "procedure_stexmrst"
    output_filename: "procedure_occurrence"

observation_period:
  data:
    visit: "visit_occurrence"
    condition: "condition_occurrence"
    drug: "drug_exposure"
    measurement: "measurement"
    procedure: "procedure_occurrence"
    output_filename: "observation_period"